# Generated by Django 5.0.4 on 2024-05-14 15:09

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0020_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(editable=False, max_length=32)),
                ('pick_up_city', models.CharField(max_length=250)),
                ('pick_up_county', models.CharField(max_length=250)),
                ('drop_off_city', models.CharField(max_length=250)),
                ('drop_off_county', models.CharField(max_length=250)),
                ('pick_up_date', models.DateField()),
                ('drop_off_date', models.DateField()),
                ('pick_up_time', models.TimeField()),
                ('drop_off_time', models.TimeField()),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('address_1', models.CharField(max_length=250)),
                ('address_2', models.CharField(blank=True, max_length=250, null=True)),
                ('town', models.CharField(max_length=100)),
                ('eir_code', models.CharField(max_length=10)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('licence_number', models.CharField(max_length=20)),
                ('licence_expiry', models.DateField()),
                ('id_number', models.CharField(max_length=20)),
                ('country_issued', django_countries.fields.CountryField(max_length=2)),
                ('id_expiry', models.DateField()),
                ('booster_seat', models.IntegerField(default=False)),
                ('booster_total', models.IntegerField(default=False)),
                ('child_seat', models.IntegerField(default=False)),
                ('childseat_total', models.IntegerField(default=False)),
                ('infant_car_capsule', models.IntegerField(default=False)),
                ('infant_total', models.IntegerField(default=False)),
                ('total_rent', models.IntegerField()),
                ('grand_total', models.IntegerField()),
                ('days', models.IntegerField()),
                ('hours', models.IntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.county')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.personaldetails')),
                ('personal_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.personalid')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.title')),
            ],
        ),
    ]
