# Generated by Django 5.0.4 on 2024-05-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
