# Generated by Django 5.0.4 on 2024-05-30 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0020_delete_booking'),
        ('checkout', '0004_alter_booking_status_alter_booking_stripe_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.personaldetails'),
        ),
    ]
