# Generated by Django 5.0.4 on 2024-04-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('rent', models.IntegerField()),
                ('fuel', models.CharField(max_length=100)),
                ('seats', models.IntegerField()),
                ('doors', models.IntegerField()),
                ('gear_box', models.CharField(max_length=100)),
                ('large_bags', models.IntegerField()),
                ('small_bags', models.IntegerField()),
                ('air_condition', models.BooleanField(default=False)),
                ('abs', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
            ],
        ),
    ]
