# Generated by Django 5.0.4 on 2024-04-14 21:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=250)),
                ('county', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'cities',
                'ordering': ['city', 'county'],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=250)),
                ('date_of_birth', models.DateField()),
                ('mobile', models.CharField(max_length=20)),
                ('address_1', models.CharField(max_length=250)),
                ('address_2', models.CharField(blank=True, max_length=250, null=True)),
                ('town', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('eir_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_location', models.CharField(max_length=250)),
                ('drop_off_location', models.CharField(max_length=250)),
                ('pick_up_date', models.DateField()),
                ('drop_off_date', models.DateField()),
                ('pick_up_time', models.TimeField()),
                ('drop_off_time', models.TimeField()),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('address_1', models.CharField(max_length=250)),
                ('address_2', models.CharField(blank=True, max_length=250, null=True)),
                ('town', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('eir_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('licence_number', models.CharField(max_length=20)),
                ('licence_expiry', models.DateField()),
                ('personal_id', models.CharField(max_length=20)),
                ('id_number', models.CharField(max_length=20)),
                ('id_expiry', models.DateField()),
                ('full_cover', models.BooleanField(default=False)),
                ('booster_seat', models.BooleanField(default=False)),
                ('child_seat', models.BooleanField(default=False)),
                ('infant_car_capsule', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.personaldetails')),
            ],
        ),
    ]
