# Generated by Django 5.0.4 on 2024-04-17 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_cities_car_city_personaldetails_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['category'],
            },
        ),
        migrations.AlterField(
            model_name='car',
            name='city',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cars.cities'),
        ),
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cars.categories'),
        ),
    ]
