# Generated by Django 5.0.4 on 2024-04-17 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_fuel_alter_car_category_alter_car_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GearBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gear_box', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['gear_box'],
            },
        ),
        migrations.AlterField(
            model_name='car',
            name='gear_box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.gearbox'),
        ),
    ]
