# Generated by Django 5.0.4 on 2024-04-17 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_gearbox_alter_car_gear_box'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.title'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.title'),
        ),
    ]
