# Generated by Django 5.0.4 on 2024-05-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_booking_booking_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'counties',
            },
        ),
        migrations.RemoveField(
            model_name='booking',
            name='full_cover',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booster_seat',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='child_seat',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='infant_car_capsule',
            field=models.IntegerField(default=False),
        ),
    ]
