# Generated by Django 5.0.4 on 2024-05-10 06:44

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_county_remove_booking_full_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='booking',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.county'),
        ),
    ]
