# Generated by Django 5.0.4 on 2024-05-11 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_alter_personaldetails_county'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_id', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Personal IDs',
                'ordering': ['personal_id'],
            },
        ),
        migrations.AlterModelOptions(
            name='county',
            options={'ordering': ['county'], 'verbose_name_plural': 'counties'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='personal_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.personalid'),
        ),
    ]
