# Generated by Django 5.0.4 on 2024-05-11 16:42

import django.utils.timezone
import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_personalid_alter_county_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='country_issued',
            field=django_countries.fields.CountryField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
