# Generated by Django 5.0.4 on 2024-05-11 17:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_booking_country_issued'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='drop_off_location',
            new_name='drop_off_city',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='pick_up_location',
            new_name='drop_off_county',
        ),
        migrations.AddField(
            model_name='booking',
            name='pick_up_city',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='pick_up_county',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
