# Generated by Django 5.0.4 on 2024-05-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_rename_drop_off_location_booking_drop_off_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booster_total',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='childseat_total',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='days',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='grand_total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='hours',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='infant_total',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_rent',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
