# Generated by Django 5.0.4 on 2024-05-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_booking_booster_total_booking_childseat_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(editable=False, max_length=10),
        ),
    ]
